admins: []
forwards:
- source: -1001713417287
  dest:
  - -1001606340133
  offset: 7
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
